# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# Configuration for CodeRabbit AI Code Reviews
# https://docs.coderabbit.ai/

# Language settings
language: ja-JP

# Review settings
reviews:
  # Enable automatic reviews for pull requests
  auto_review:
    enabled: true
  
  # Include draft pull requests in reviews
  include_drafts: false
  
  # Review request on push to pull request
  review_on_push: true

# Chat settings
chat:
  # Enable chat functionality
  auto_reply: false

# Knowledge base settings
knowledge_base:
  # Opt in to learnings from your codebase
  learnings:
    enabled: true
  
  # Enable insights from your repository
  insights: true

# Tone and style (shortened to under 250 characters)
tone_instructions: "Rails 8のベストプラクティス、セキュリティ、保守性、パフォーマンス、CSSアーキテクチャ、エラーハンドリング、一貫したコードスタイルに重点を置いてレビューしてください。"

# Early access features
early_access: false
