# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# Configuration for CodeRabbit AI Code Reviews
# https://docs.coderabbit.ai/

# Language settings
language: en-US

# Review settings
reviews:
  # Enable automatic reviews for pull requests
  auto_review:
    enabled: true
  
  # Include draft pull requests in reviews
  include_drafts: false
  
  # Review request on push to pull request
  review_on_push: true

# Chat settings
chat:
  # Enable chat functionality
  auto_reply: false

# Path-based settings
path_filters:
  # Files to always review
  include:
    - "**/*.rb"
    - "**/*.js"
    - "**/*.ts"
    - "**/*.css"
    - "**/*.scss"
    - "**/*.erb"
    - "**/*.yml"
    - "**/*.yaml"
    - "Gemfile"
    - "Dockerfile"
    
  # Files to exclude from review
  exclude:
    - "node_modules/**"
    - "vendor/**"
    - "log/**"
    - "tmp/**"
    - "storage/**"
    - "public/assets/**"
    - "app/assets/builds/**"
    - "db/schema.rb"
    - "*.lock"
    - "*.min.js"
    - "*.min.css"

# Knowledge base settings
knowledge_base:
  # Opt in to learnings from your codebase
  learnings:
    enabled: true
  
  # Enable insights from your repository
  insights: true

# Tone and style (shortened to under 250 characters)
tone_instructions: "Focus on Rails 8 best practices, security, maintainability, performance, CSS architecture, error handling, and consistent code style."

# Early access features
early_access: false