inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'config/puma.rb'
    - 'config/boot.rb'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/routes.rb'
    - 'config/initializers/*'
    - 'test/**/*'
    - 'app/views/**/*.erb'  # ERBファイルはerb-lintで管理

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false